# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-11 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Last name')),
                ('model_pic', models.ImageField(null=True, upload_to='enemy/')),
                ('description', models.CharField(max_length=1024, null=True, verbose_name='Description')),
                ('address', geoposition.fields.GeopositionField(max_length=42, null=True, verbose_name='Address')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='City')),
            ],
        ),
    ]
