# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-11 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='model_pic',
            new_name='avatar',
        ),
        migrations.AlterField(
            model_name='enemy',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя врага'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Его фамилия'),
        ),
    ]
