# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-11 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('enemies', '0002_auto_20170611_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country', verbose_name='Страна проживания'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='address',
            field=geoposition.fields.GeopositionField(max_length=42, null=True, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='avatar',
            field=models.ImageField(null=True, upload_to='enemy/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='description',
            field=models.CharField(max_length=1024, null=True, verbose_name='Описания злодеяний'),
        ),
    ]
